services:
  mongodb:
    image: mongo:${MONGODB_VERSION:-5.0}
    container_name: eyrie_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: eyrie
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - eyrie-network
      
  eyrie-backend:
    image: clinicalgenomicslund/eyrie-backend:${BACKEND_VERSION:-latest}
    container_name: eyrie_backend
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/eyrie}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      BACKEND_BASE_PATH: ${BACKEND_BASE_PATH:-/api}
    ports:
      - "${BACKEND_HOST_PORT:-8000}:5000"
    depends_on:
      - mongodb
    networks:
      - eyrie-network

  eyrie-frontend:
    image: clinicalgenomicslund/eyrie-frontend:${FRONTEND_VERSION:-latest}
    container_name: eyrie_frontend
    restart: unless-stopped
    environment:
      INTERNAL_BACKEND_URL: ${INTERNAL_BACKEND_URL:-http://eyrie_backend:5000}
      EXTERNAL_BASE_PATH: ${EXTERNAL_BASE_PATH:-}
      EXTERNAL_API_URL: ${EXTERNAL_API_URL:-http://localhost:8000/api}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      TRANA_ANALYSIS_RESULTS: ${TRANA_ANALYSIS_RESULTS:-/app/analysis-files/results/trana}
      METAVAL_ANALYSIS_RESULTS: ${METAVAL_ANALYSIS_RESULTS:-/app/analysis-files/results/metaval}
      EYRIE_ANALYSIS_OUTPUT_DIRPATH: ${EYRIE_ANALYSIS_OUTPUT_DIRPATH:-./analysis-files/results/trana:}
    ports:
      - "${FRONTEND_HOST_PORT:-3000}:5000"
    depends_on:
      - eyrie-backend
    volumes:
      - ${EYRIE_ANALYSIS_OUTPUT_DIRPATH:-./analysis-files/results/trana:}:${TRANA_ANALYSIS_RESULTS:-/app/analysis-files/results/trana}:ro
    networks:
      - eyrie-network

volumes:
  mongodb_data:

networks:
  eyrie-network:
    driver: bridge
    name: eyrie-network
