name: Publish on Release

on:
  release:
    types: [published]

jobs:
  publish-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract frontend version
      id: frontend-version
      run: |
        VERSION=$(grep -oP '__version__ = "\K[^"]+' frontend/eyrie_app/__version__.py)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          clinicalgenomicslund/eyrie-frontend:${{ steps.frontend-version.outputs.version }}
          clinicalgenomicslund/eyrie-frontend:latest
        platforms: linux/amd64,linux/arm64

  publish-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract backend version
      id: backend-version
      run: |
        VERSION=$(grep -oP '__version__ = "\K[^"]+' backend/eyrie_api/__version__.py)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          clinicalgenomicslund/eyrie-backend:${{ steps.backend-version.outputs.version }}
          clinicalgenomicslund/eyrie-backend:latest
        platforms: linux/amd64,linux/arm64
